import Head from "next/head";
import styles from "../styles/Home.module.css";

// We import sheetData from getServerSideProps
export default function Sheet({ sheetdata }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* we place sheet data in text */}
        <h1 className={styles.title}>{console.log(sheetdata)}</h1>
        {/* Load Headers */}
        {sheetdata.headers.headerText.map((value, index) => {
          return (
            <h1 class="header" id={index}>
              {value}
            </h1>
          );
        })}
        {/* Load Entries */}

        {sheetdata.entries.entryText.map((value, index) => {
          return (
            <p class="entries" key={sheetdata.entries.headerIndex[index]}>
              {value}
            </p>
          );
        })}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const URL = process.env.URL;
  console.log(URL + "/api/privateSheet");
  const req = await fetch(URL + "/api/privateSheet");

  const res = await req.json();

  return {
    props: {
      sheetdata: res.data,
    },
  };
}
