import Head from "next/head";
import styles from "../styles/Home.module.css";

// We import sheetData from getServerSideProps
export default function Sheet({ sheetdata }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {sheetdata.map((value, index) => {
          return (
            <article class="sheet">
              <h1 class="sheetTitle">{value.title}</h1>

              {/* Load Headers */}
              {sheetdata[index].headers.map((value, index) => {
                return (
                  <section id={index}>
                    <h2 class={"header, " + index}>
                      <pre>{value.headerText}</pre>
                    </h2>

                    {/* Load Entries */}
                    {value.headerEntries.map((value, index) => {
                      return (
                        <div>
                          <h4
                            class={"entryInstruction, " + value.headerIndex}
                            key={index}
                          >
                            <pre>{value.entryInstruction}</pre>
                          </h4>
                          <pre
                            class={"entryDetails, " + value.headerIndex}
                            key={index}
                          >
                            {value.entryDetails}
                          </pre>
                        </div>
                      );
                    })}
                  </section>
                );
              })}
            </article>
          );
        })}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const URL = process.env.URL;
  console.log(URL + "/api/privateSheet");
  const req = await fetch(URL + "/api/privateSheet");

  const res = await req.json();

  return {
    props: {
      sheetdata: res.data,
    },
  };
}
